// src/data/presets.js
export const presets = [
    {
      id: '1',
      name: 'Sunset Glow',
      downloadLink: '',
      description: 'Enhance your photos with a warm sunset glow, perfect for beach scenes and evening shots.',
      image: '/bg1.jpg', // Replace with actual image URL
      date:'01-08-2024',
      category: 'Urban',
    },
    {
      id: '2',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg2.jpg',
      description: 'Tera mera sath',
      date: '2024-09-02',
      category: 'Urban',
    },
    {
      id: '3',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg3.jpg',
      description: 'Humnava mere ',
      date: '2024-09-03',
      category: 'Portrait',
    },
    {
      id: '4',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg4.jpg',
      description: 'suna he suna he ye phli dfa he',
      date: '2024-09-04',
      category: 'Landscape',
    },
    {
      id: '5',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg5.jpg',
      description: 'Tere liye sirf tere liye aesthetic',
      date: '2024-09-05',
      category: 'Vintage',
    },
    {
      id: '6',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg6.jpg',
      description: 'ha hasi ban gaye ha nmi dark',
      date: '2024-09-06',
      category: 'Black & White',
    },{
      id: '7',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg3.jpg', // Placeholder image URL
      description: 'dard dilo k kam ho jate 15august',
      date: '2024-09-01',
      category: 'Nature',
    },
    {
      id: '8',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg6.jpg',
      description: 'tere bina jindagi me koi sikwa to nhi velentine',
      date: '2024-09-02',
      category: 'Urban',
    },
    {
      id: '9',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg2.jpg',
      description: 'Preset 3 description couples',
      date: '2024-09-03',
      category: 'Portrait',
    },
    {
      id: '10',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg5.jpg',
      description: 'Preset 4 description eid',
      date: '2024-09-04',
      category: 'Landscape',
    },
    {
      id: '11',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg4.jpg',
      description: 'Preset 5 description diwali',
      date: '2024-09-05',
      category: 'Vintage',
    },
    {
      id: '12',
      name: 'Sunset Glow',
      downloadLink: '',
      image: '/bg1.jpg',
      description: 'Preset 6 description travel',
      date: '2024-09-06',
      category: 'Black & White',
    },
    // Add more presets as needed
  ];
  